import { HttpError } from './store';

export async function boundedBody(request: Request, limit: number) {
  if (Number(request.headers.get('content-length')) > limit) throw new HttpError(413, 'Файл або запит завеликий.');
  const reader = request.body?.getReader();
  if (!reader) return new Uint8Array();
  const chunks: Uint8Array[] = [];
  let size = 0;
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    size += value.byteLength;
    if (size > limit) { await reader.cancel(); throw new HttpError(413, 'Файл або запит завеликий.'); }
    chunks.push(value);
  }
  const bytes = new Uint8Array(size);
  let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.length; }
  return bytes;
}

// Accept only the small, non-animated WebP container generated by canvas.
// This validates structure/dimensions, not the entire compressed pixel stream.
// Images are served with a fixed image MIME type and nosniff, never as HTML.
export function validWebp(bytes: Uint8Array) {
  if (bytes.length < 30) return false;
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const tag = (offset: number) => String.fromCharCode(...bytes.subarray(offset, offset + 4));
  const u24 = (offset: number) => bytes[offset] | bytes[offset + 1] << 8 | bytes[offset + 2] << 16;
  if (tag(0) !== 'RIFF' || tag(8) !== 'WEBP' || view.getUint32(4, true) + 8 !== bytes.length) return false;
  let offset = 12;
  let imageCount = 0;
  let width = 0;
  let height = 0;
  let extended = false;
  let profile = false;
  while (offset + 8 <= bytes.length) {
    const kind = tag(offset);
    const length = view.getUint32(offset + 4, true);
    const start = offset + 8;
    const end = start + length;
    if (!length || end > bytes.length) return false;
    if (kind === 'VP8X') {
      if (offset !== 12 || length !== 10 || (bytes[start] & ~0x30) !== 0) return false;
      extended = true;
      width = u24(start + 4) + 1; height = u24(start + 7) + 1;
    } else if (kind === 'ICCP') {
      // Chromium includes its color profile; allow it, but no EXIF/XMP or animation.
      if (!extended || profile || imageCount || length > 65536) return false;
      profile = true;
    } else if (kind === 'VP8 ') {
      if (length < 10 || bytes[start] & 1 || bytes[start + 3] !== 0x9d || bytes[start + 4] !== 1 || bytes[start + 5] !== 0x2a) return false;
      const w = view.getUint16(start + 6, true) & 0x3fff;
      const h = view.getUint16(start + 8, true) & 0x3fff;
      if (extended && (w !== width || h !== height)) return false;
      width = w; height = h; imageCount++;
    } else if (kind === 'VP8L') {
      if (length < 5 || bytes[start] !== 0x2f || bytes[start + 4] >> 5) return false;
      const bits = view.getUint32(start + 1, true);
      const w = (bits & 0x3fff) + 1;
      const h = ((bits >>> 14) & 0x3fff) + 1;
      if (extended && (w !== width || h !== height)) return false;
      width = w; height = h; imageCount++;
    } else if (kind !== 'ALPH' || !extended || imageCount) return false;
    offset = end + (length % 2);
  }
  return offset === bytes.length && imageCount === 1 && width > 0 && height > 0 && width <= 1600 && height <= 1600;
}
